site_name: Airflux serialization

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Readers: readers.md
  - Writers: writers.md
  - Environment: env.md
  - Standard tools: standard-tools.md

theme:
  language: en
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt
repo_url: https://github.com/airflux/airflux-serialization
repo_name: airflux/airflux-serialization
edit_uri: ""

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
