# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PRIVATE_PASSWORD: ${{ secrets.GPG_PRIVATE_PASSWORD }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build publish
    - name: Generate JaCoCo Badges for Core module
      id: jacocoCoreModule
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: core/build/reports/jacoco/test/jacocoTestReport.csv
        coverage-badge-filename: jacocoCoreModule.svg
        branches-badge-filename: branchesCoreModule.svg
    - name: Generate JaCoCo Badges for DSL module
      id: jacocoDSLModule
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: dsl/build/reports/jacoco/test/jacocoTestReport.csv
        coverage-badge-filename: jacocoDSLModule.svg
        branches-badge-filename: branchesDSLModule.svg
    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Maxim Sambulat'
          git config --global user.email 'mx.smblt@gmail.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi
